* configure: Regen.         * tcljava.m4 (AC_GCC_BUGS):         Replace AC_TRY_COMPILE with AC_TRY_RUN so         that program is compiled and run on host system. 	[Bug 1528278]

diff --git a/tcljava/configure b/tcljava/configure
--- a/tcljava/configure
+++ b/tcljava/configure
@@ -4448,7 +4448,10 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
         ac_saved_cflags=$CFLAGS
         CFLAGS="$CFLAGS -O2"
-        cat >conftest.$ac_ext <<_ACEOF
+        if test "$cross_compiling" = yes; then
+  ac_java_gcc_optimizer_bug=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
 _ACEOF
@@ -4456,30 +4459,24 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-int
-main ()
-{
-
-            void * p= (void *) 0xcccccccc;
-            unsigned long long int x = 0;
-            *((void **)&x) = p;
-            if (x == 0xcccccccc) {
+            int main(int argc, char **argv) {
+              void * p= (void *) 0xcccccccc;
+              unsigned long long int x = 0;
+              *((void **)&x) = p;
+              if (x == 0xcccccccc) {
                 return 0;
-            } else {
+              } else {
                 return 1;
+              }
             }
 
-  ;
-  return 0;
-}
 _ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -4487,12 +4484,15 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (exit $ac_status); }; }; then
   ac_java_gcc_optimizer_bug=no
 else
-  echo "$as_me: failed program was:" >&5
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
+( exit $ac_status )
 ac_java_gcc_optimizer_bug=yes
 fi
-rm -f conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
         ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
